"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(dotenv_path):
    if not dotenv_path.exists():
        
        return
    for raw_line in dotenv_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def env(name, default=None, aliases=()):
    for key in (name, *aliases):
        value = os.getenv(key)
        if value not in (None, ""):
            return value
    return default


def env_bool(name, default=False, aliases=()):
    value = env(name, aliases=aliases)
    if value in (None, ""):
        return default
    return value.lower() in {"true", "1", "yes", "on"}


def env_list(name, default=(), aliases=()):
    value = env(name, aliases=aliases)
    if not value:
        return list(default)
    return [item.strip() for item in value.split(",") if item.strip()]


_load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', 'dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
IS_RAILWAY = bool(env("RAILWAY_ENVIRONMENT"))
DEBUG = env_bool("DEBUG", default=not IS_RAILWAY)

APP_SCHEME = env("APP_SCHEME", "https" if IS_RAILWAY else "http")
APP_DOMAIN = env("APP_DOMAIN", "ledgerpro.com" if IS_RAILWAY else "127.0.0.1:8000")
APP_HOST = APP_DOMAIN.split(":", 1)[0]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=False)
SECURE_HSTS_SECONDS = int(env("SECURE_HSTS_SECONDS", 0))

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", default=[
    "ledgerpro.com",
    "www.ledgerpro.com",
    ".railway.app",
    "127.0.0.1",
    "localhost",
])
if APP_HOST and APP_HOST not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(APP_HOST)

CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", default=[
    "https://ledgerpro.com",
    "https://www.ledgerpro.com",
    "https://*.railway.app",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
])
app_origin = f"{APP_SCHEME}://{APP_DOMAIN}"
if app_origin not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(app_origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'main.apps.MainConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'main.middleware.TwoFactorEnforcementMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Prioritize project templates (including account/* overrides) before app templates.
        'DIRS': [BASE_DIR / 'main' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.google_oauth',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = env("DATABASE_URL", aliases=("MYSQL_URL", "MYSQL_PUBLIC_URL"))
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=env_bool("DB_SSL_REQUIRE", default=False),
        )
    }
else:
    # MySQL configuration; environment variables make it easy to change credentials.
    DATABASES = {
        'default': {
            'ENGINE': env('DB_ENGINE', 'django.db.backends.mysql', aliases=('MYSQL_ENGINE',)),
            'NAME': env('DB_NAME', 'main_db', aliases=('MYSQL_DATABASE',)),
            'USER': env('DB_USER', 'root', aliases=('MYSQL_USER',)),
            'PASSWORD': env('DB_PASSWORD', '', aliases=('MYSQL_PASSWORD',)),
            'HOST': env('DB_HOST', '127.0.0.1', aliases=('MYSQL_HOST',)),
            'PORT': env('DB_PORT', '3306', aliases=('MYSQL_PORT',)),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (uploads: images, documents, etc.)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# allauth / auth configuration
SITE_ID = 1
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/login/'
ACCOUNT_DEFAULT_HTTP_PROTOCOL = APP_SCHEME
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
ACCOUNT_LOGOUT_REDIRECT_URL = '/login/'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_ADAPTER = 'main.adapters.CustomSocialAccountAdapter'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'VERIFIED_EMAIL': True,
        'APP': {
            'client_id': env('GOOGLE_CLIENT_ID', ''),
            'secret': env('GOOGLE_CLIENT_SECRET', ''),
            'key': '',
        },
    }
}

# Keep the allauth OAuth state in the same browser session for local development.
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', default=APP_SCHEME == 'https')
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', default=APP_SCHEME == 'https')
ENFORCE_2FA = env('ENFORCE_2FA', 'False').lower() in {'true', '1', 'yes', 'on'}

# Email backend (Gmail SMTP example)
# Use an App Password if 2FA is enabled on Gmail.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(env('EMAIL_PORT', 587))
EMAIL_USE_TLS = env('EMAIL_USE_TLS', 'True').lower() in {'true', '1', 'yes'}
EMAIL_HOST_USER = env('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
TOTP_ISSUER_NAME = env('TOTP_ISSUER_NAME', 'LedgerPro')
